<div class="record-container">
  <div class="holding-details">
    <div class="callnumAndLocation">
      <div class="clearfix">
        <?php foreach ($items as $index => $item) : ?>
          <div class="holdings" data-rows="<?= $index; ?>">
            <div class="<?= ($index % 2) ? "odd" : "even"; ?>">
              <div class="no-branches">
                <div class="groupLocation">
                  <i class="fa <?= ($index % 2) ? "fa-remove text-error" : "fa-ok text-success"; ?>"></i> <span class="text-<?= ($index % 2) ? "remove" : "ok"; ?>"><span class="branch"><?= $item['location']; ?></span></span>
                </div>
                <div class="groupCallnumber">
                  <div class="location-link-text">
                    <?= $item['callnumber']; ?>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <?php endforeach; ?>
      </div>
    </div>
  </div>
</div>
