<form class="search-form form-inline <?= $wrapperClass ?? '' ?>">
  <div class="input-group">
    <input class="form-control" type="text" aria-label="<?= $label; ?>" placeholder="<?= $placeholder ?? ''; ?>" aria-placeholder="<?= $placeholder ?? ''; ?>" />
    <button type="submit" class="btn btn-primary">
      <i class="fa fa-search" aria-hidden="true"></i>
      <span class="sr-only"><?= $label; ?></span>
    </button>
  </div>
</form>
