<div class="service-point-info <?= $wrapperClass ?? ''; ?>" data-organisation="<?= $organisation ?? ''; ?>" data-service-point-id="<?= $servicePointId ?? ''; ?>">
  <?= $this->render('components/atoms/messaging/loader/loader.phtml', ['wrapperClass' => 'service-point-loader js-loader']); ?>
  <div class="service-point-info-wrapper hide js-service-point-info">
    <div class="service-point">
      <h3 class="service-point-title js-service-point-title"></h3>
      <p class="service-point-address js-service-point-address"></p>
      <div class="service-point-links">
        <a href="#" target="_blank" class="service-point-link js-directions">
          <i class="fa fa-bus" aria-hidden="true"></i> <?= $directionsText; ?>
        </a>
        <a href="#" target="_blank" class="service-point-link js-homepage">
          <i class="fa fa-home"></i> <?= $homepageText; ?>
        </a>
      </div>
      <p class="service-point-email">
        <i class="fa fa-envelope" aria-hidden="true"></i>
        <span class="js-service-point-email"></span>
      </p>
    </div>
    <div class="service-point-opening-times">
      <h3 class="opening-times-title js-open-today">
        <span class="open js-hide-on-load hide"><?= $openText; ?></span>
        <span class="closed js-hide-on-load hide"><?= $closedText; ?></span>
      </h3>
      <p class="opening-times-today js-opening-times js-hide-on-load">
        <i class="fa fa-clock-o" aria-hidden="true"></i> <?= $openTodayText; ?>
        <span class="opens js-opens"></span> - <span class="closes js-closes"></span>
        <span class="js-staff-times hide js-hide-on-load">
          (<?= $staffAvailableText; ?>
          <span class="opens js-staff-opens"></span> - <span class="closes js-staff-closes"></span>)
        </span>
      </p>
    </div>
    <div class="service-point-social-media">
      <a class="js-facebook hide js-hide-on-load" aria-label="Facebook" href="" target="_blank">
        <i class="fa fa-facebook" aria-hidden="true"></i>
      </a>
    </div>
    <div class="service-point-slogan">
      <p class="js-slogan hide js-hide-on-load"></p>
    </div>
  </div>
</div>
<?php
$js = <<<JS
 $(document).ready(function onDocumentReady() {
    var initServicePointInfo = function initServicePointInfo() {
      var id = '{$servicePointId}';

      var servicePointInfo = finna.servicePointInfo(this.document);

      servicePointInfo.init($('.{$wrapperClass}'), finna.organisationInfo);
      servicePointInfo.getServicePoint(id);
    };

    if (!finna.servicePointInfo || !finna.organisationInfo) {
      return;
    }

    initServicePointInfo();
  });
JS;

echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $js, 'SET');
?>
