<form class="add-keyword-form form-group js-add-keyword" novalidate>
  <label for="keyword" class="add-keyword-form__label"><?= $form['label'] ?></label>
  <div class="add-keyword-form__input-wrapper">
    <input class="add-keyword-form__input form-control" type="text" name="keyword" id="keyword" aria-required="true" required />
    <button type="submit" class="btn btn-primary add-keyword-form__button">
      <?= $form['submit'] ?>
    </button>
  </div>
  <div class="add-keyword-form__error">
    <?= $form['error'] ?>
  </div>
</form>
