<form class="form-vertical">
  <div class="form-group">
    <label for="pl-input-text"><?= $form['label']; ?></label>
    <input class="form-control" id="pl-input-text" name="pl-input-text" placeholder="<?= $form['inputPlaceholder'] ?>" aria-placeholder="<?= $form['inputPlaceholder'] ?>" type="text" />
  </div>
  <div class="form-group">
    <label for="pl-input-text"><?= $form['label']; ?></label>
    <input class="form-control invalid" id="pl-input-text" name="pl-input-text" placeholder="<?= $form['inputPlaceholderInvalid'] ?>" aria-placeholder="<?= $form['inputPlaceholderInvalid'] ?>" type="text" />
  </div>
</form>
