<table class="table">
  <thead>
    <tr>
      <?php foreach ($head as $item) : ?>
        <th scope="col"><?= $item; ?></th>
      <?php endforeach; ?>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($body as $index => $item) : ?>
      <tr>
        <th scope="row"><?= $index + 1; ?></th>
        <?php foreach ($item as $key => $value) : ?>
          <td><?= $value; ?></td>
        <?php endforeach; ?>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
