<div class="keywords">
  <?= $this->render('components/atoms/messaging/loader/loader.phtml', ['wrapperClass' => 'keywords-spinner js-spinner']); ?>
  <div class="keywords-wrapper js-keywords-wrapper">
    <?php if (isset($editable) && $editable) : ?>
      <button class="keywords-toggle__button btn js-toggle-keywords" aria-label="<?= $toggleButtonLabel; ?>">
        <span class="keywords-toggle__label"><?= $addKeyword ?></span>
        <i class="fa fa-tag keywords-toggle__icon" aria-hidden="true"></i>
      </button>
      <div class="keywords-controls js-controls">
        <?= $this->render(
          'components/molecules/messaging/in-testing-alert/in-testing-alert.phtml',
          ['alert' => $alert]
        ); ?>
        <?= $this->render('components/molecules/forms/add-keyword/add-keyword.phtml', ['label' => $form['label'], 'submit' => $submit, 'errorMessage' => $form['error']]); ?>
      </div>
    <?php endif; ?>
    <div class="keywords-current js-current">
      <?php if (isset($editable) && $editable) : ?>
        <p class="keywords-current__text">
          <?= $currentKeywords ?>
          (<span class="js-keywords-counter">0</span>):
        </p>
      <?php endif; ?>
      <div class="keywords-current__list js-keywords-list"></div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function() {
    finna.keywords.init();
  });
</script>
