<div class="schedule-widget organisation-info <?= $wrapperClass; ?>" data-organisation="<?= $organisation; ?>" data-target="<?= $target ?? 'page'; ?>" data-service-point-id="<?= $servicePointId; ?>">
  <?php if (isset($widgetHeading)) : ?>
    <h2><?= $widgetHeading; ?></h2>
  <?php endif; ?>
  <?= $this->render('components/atoms/messaging/loader/loader.phtml', ['wrapperClass' => 'loader js-inital-loader']); ?>
  <div class="js-hidden-initally hide">
    <div class="info-col">
      <?= $this->render('components/molecules/scheduling/service-point-schedule/service-point-schedule.phtml', ['organisation' => $organisation, 'servicePointId' => $servicePointId, 'previousWeekLabel' => $previousWeekLabel, 'weekText' => $weekText, 'nextWeekLabel' => $nextWeekLabel, 'informationNotAvailableText' => $informationNotAvailableText, 'wrapperClass' => $scheduleWrapperClass, 'staffAvailableText' => $staffAvailableText, 'selfServiceText' => $selfServiceText, 'openText' => $openText, 'closedText' => $closedText, 'dropdownFallbackLabel' => $dropdownFallbackLabel, 'showControls' => true, 'weekNaviStatusText' => $weekNaviStatusText, 'dropdownStatusText' => $dropdownStatusText]) ?>
    </div>
    <?= $this->render('components/atoms/messaging/loader/loader.phtml', ['wrapperClass' => 'loader js-details-loader']); ?>
    <div class="details-col js-details-colum">
      <a href="" data-href="<?= $facilityLink ?? ''; ?>" aria-label="<?= $moreInfoLabel ?? ''; ?>">
        <img src="<?= $facilityPlaceholderImage ?? ''; ?>" alt="<?= $moreInfoLabel ?? ''; ?>" class="js-facility-image facility-image" />
      </a>
      <div class="details-wrapper">
        <div class="details-item">
          <?= $this->render('components/atoms/tooltips/tooltip/tooltip.phtml', ['buttonClasses' => ['btn js-hide-onload hide js-email'], 'position' => 'bottom', 'buttonText' => "<i class='fa fa-at' aria-hidden='true'></i><span class='sr-only'>" . ($emailText ?? '') . "</span>", 'content' => ""]) ?>
          <?= $this->render('components/atoms/tooltips/tooltip/tooltip.phtml', ['buttonClasses' => ['btn js-hide-onload hide js-phone'], 'position' => 'bottom', 'buttonText' => "<i class='fa fa-phone-square' aria-hidden='true'></i><span class='sr-only'>" . ($phoneText ?? '') . "</span>", 'content' => ""]) ?>
          <a href="" target="_blank" class="js-route js-hide-onload hide btn">
            <i class="fa fa-bus" aria-hidden="true"></i>
            <span class="sr-only"><?= $directionsText ?? ''; ?> (<?= $externalLinkText ?? ''; ?>)</span>
          </a>
          <a href="" target="_blank" class="js-facebook js-hide-onload hide btn">
            <i class="fa fa-facebook-square" aria-hidden="true"></i>
            <span class="sr-only"><?= $facebookText ?? ''; ?> (<?= $externalLinkText ?? ''; ?>)</span>
          </a>
        </div>
        <div class="js-map js-hide-onload hide details-item">
          <a href="" target="_blank">
            <i class="fa fa-map-marker" aria-hidden="true">
            </i>
            <span class="js-map-address"></span>
          </a>
        </div>
        <div class="js-details-link js-hide-onload hide details-item">
          <a href="" data-href="<?= $facilityLink ?? ''; ?>">
            <i class="fa fa-home" aria-hidden="true"></i>
            <?= $servicePointInfoText ?? ''; ?>
          </a>
        </div>
        <div class="js-services details-item">
          <span class="service-item js-service-wifi js-hide-onload hide" aria-label="<?= $wifiText ?? ''; ?>">
            <i class="fa fa-wifi" aria-hidden="true"></i>
          </span>
          <span class="service-item js-service-print js-hide-onload hide" aria-label="<?= $printText ?? ''; ?>">
            <i class="fa fa-print" aria-hidden="true"></i>
          </span>
        </div>
      </div>
    </div>
  </div>
</div>
<?php
$js = <<<JS
$(document).ready(function onDocumentReady() {
    var initSchedulingWidget = function initSchedulingWidget() {
      var widget = finna.scheduleWidget(this.document);

      widget.init($('.{$wrapperClass}'), finna.organisationInfo);
      widget.getServicePointInfo();
    };

    if(!finna.scheduleWidget || !finna.organisationInfo) {
      return;
    }

    initSchedulingWidget();
  });
JS;

echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $js, 'SET');
?>
