<ul class="sg-colors">
  <?php foreach ($items as $item) : ?>
    <li>
      <span class="sg-swatch" style="background: <?= $item['value'] ?>;"></span>
      <span class="sg-label">
        <?= $item['name'] ?>
        <br />
        <?= $item['value'] ?>
        <br />
        <?= $item['comment'] ?>
      </span>
    </li>
  <?php endforeach; ?>
</ul>
<!--end sg-colors-->

<small><?= $meta['description'] ?></small>
