<!-- START of: finna - organisationinfo/home-consortium.phtml -->
<div class="organisation-info-page loading organisation-page-information-wrapper">
  <div class="loader">
    <i class="fa fa-spinner fa-spin" style="text-align: center;"></i>
  </div>

  <?php $building = "0/{$this->id}/"; ?>
  <?php $consortiumSearch = $this->url('search-results', [], ['query' => ['filter' => $this->buildingFacetOperator . 'building:"' . $building . '"']])?>

  <div class="consortium-info hide navi-section" id="consortium-info-section">
    <div>
      <h1 class="name">-</h1>
      <div class="consortium-info-row">
        <div class="consortium-logo js-consortium-logo">
          <?=$this->render('components/molecules/media/figure-with-caption/figure-with-caption.phtml', ['imgSrc' => '', 'caption' => ''])?>
        </div>
        <div class="description"><?=$this->translate('organisation_no_consortium_info_html');?></div>
        <div class="consortium-search-usage">
          <span class="consortium-search">
            <a href="<?= $this->escapeHtmlAttr($consortiumSearch) ?>"><i class="fa fa-search"></i> <?= $this->transEsc('organisation_info_search'); ?></a>
          </span>
          <span class="gauge-meter hide">
            <canvas width="75" height="60" class="finna-coverage-gauge"></canvas>
            <span class="gauge-value"><span class="val"></span> %</span>
            <span class="gauge-label"><?=$this->translate('organisation_info_coverage')?></span>
          </span>
        </div>
        <?=$this->render('components/molecules/accordion/accordion/accordion.phtml', ['content' => $this->translate('organisation_no_consortium_info_html'), 'contentId' => 'usageContent', 'title' => $this->translate('organisation_info_navi_usage'), 'titleId' => 'usageTitle', 'outline' => true, 'wrapperClass' => 'js-usage-accordion'])?>
        <br>
        <?=$this->render('components/molecules/accordion/accordion/accordion.phtml', ['content' => '<h4>'.$this->translate('organisation_info_page_finna_link').'</h4>', 'contentId' => 'linksContent', 'title' => $this->translate('Links'), 'titleId' => 'linksTitle', 'outline' => true, 'wrapperClass' => 'js-links-accordion'])?>
      </div>
    </div>
    <div class="organisation-list" data-rows="1"><ul></ul></div>
  </div>
</div>
<?php // close enclosing container div to make layout fluid again ?>
</div>


<div class="last-section">
  <div class="container organisation-info-page loading organisation-page-information-wrapper">
    <?=$this->render('organisationinfo/map-information.phtml', ['consortiumInfo' => true, 'id' => $this->id])?>
  </div>
</div>
<?php // re-open the closed container div ?>
<div class="container">
<!-- END of: finna - organisationinfo/home-consortium.phtml -->
