<div class="record-accordions record-tabs <?= $menuClass ?? ''; ?>">
  <a id="tabnav"></a>
  <div class="finna-record-tabs tabs-responsive">
    <?= $this->render('components/molecules/navigation/tabs/tabs-record.phtml', ['label' => $tablistLabel, 'tabs' => $tabs, 'tablistClass' => 'visible-md visible-lg']) ?>
    <div class="record-accordions">
      <?php foreach ($tabs as $tab) : ?>
        <div class="accordion <?= isset($tab['active']) && $tab['active'] ? 'active' : ''; ?>">
          <div class="accordion-toggle">
            <a href="<?= $tab['href']; ?>" class="accordion-title" data-tab="<?= $tab['id']; ?>">
              <span class="title"><?= $tab['label'] ?? $tab['name']; ?></span>
              <i class="icon" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      <?php endforeach; ?>
    </div>
    <div class="tab-content"></div>
  </div>
</div>
